services:
  app:
    environment:
      - DEBUG=true
    ports:
      - "${APP_HOST_MACHINE_PORT:-8000}:8000"
    volumes:
      - type: bind
        source: ./src
        target: /my-work
    build: ./docker/app
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?review .env}
      - MYSQL_USER=${DB_USER:?review .env}
      - MYSQL_PASSWORD=${DB_PASSWORD:?review .env}
      - MYSQL_DATABASE=${DB_DATABASE:?review .env}
      - TZ=Asia/Tokyo
    ports:
      - "${DB_HOST_MACHINE_PORT:-3306}:3306"
    volumes:
      - type: volume
        source: db-compose-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
    image: mysql:8.4.0
  mail:
    environment:
      - TZ=Asia/Tokyo
      - MP_DATABASE=/data/mailpit.db
    ports:
      - "${MAIL_HOST_MACHINE_PORT:-8025}:8025"
    volumes:
      - type: volume
        source: mail-compose-volume
        target: /data
    image: axllent/mailpit:v1.18
volumes:
  db-compose-volume:
  mail-compose-volume:
