services:
  app:
    ports: -"8000:8000"
    volumes:
      - type: bind
        source: ./src
        destination: /my-work
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
    ports: -"3306:3306"
    volumes:
      - type: volume
        source: db-compose-volume
        destination: /var/lib/mysql
      - type: bind
        source: ./docker/db/init
        destination: /docker-entrypoint-initdb.d
    image: mysql:8.4.0
  mail:
    environment:
      - TZ=Asia/Tokyo
      - MP_DATABASE=/data/mailpit.db
    ports: -"8025:8025"
    volumes:
      - type: volume
        source: mail-compose-volume
        destination: /data
    image: axllent/mailpit:v1.18
volumes:
  db-compose-volume:
  mail-compose-volume:
